# Generated by Django 6.0.6 on 2026-07-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiquest',
            old_name='course_description',
            new_name='course_duration',
        ),
    ]
